### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/dataset-browser#1]
`docker build .` fails with:

```
 => ERROR [stage-1 5/8] COPY --from=builder /app/public ./public                                                     0.0s
------
 > [stage-1 5/8] COPY --from=builder /app/public ./public:
------
failed to compute cache key: "/app/public" not found: not found
```

This repo has no `public/` dir. Should we remove that part from the Dockerfile? If so, which build directory contains the generated `index.html`?

**Comment by GertjanFi** [comment]
Fixed. Local build is more forgiving and simply creates an empty ./public folder. That line is now removed. 

Regarding the index.html -> it is located in the /.next folder that is copied in the next line of the docker file. 

Just ran and deployment action now succeeds.
